version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'

  postgres:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${CLOUDSERVICE_DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${CLOUDSERVICE_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${CLOUDSERVICE_DB_NAME:-cloudservice}
    ports:
      - '${CLOUDSERVICE_DB_PORT:-5432}:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -p 5432 -U postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CLOUDSERVICE_DB_HOST=${CLOUDSERVICE_DB_HOST:-postgres}
      - CLOUDSERVICE_DB_PORT=${CLOUDSERVICE_DB_PORT:-5432}
      - CLOUDSERVICE_DB_NAME=${CLOUDSERVICE_DB_NAME:-cloudservice}
      - CLOUDSERVICE_DB_USERNAME=${CLOUDSERVICE_DB_USERNAME:-postgres}
      - CLOUDSERVICE_DB_PASSWORD=${CLOUDSERVICE_DB_PASSWORD:-postgres}
#        depends_on:
#            postgres:
#                condition: service_healthy
