spring:
    datasource:
        url: jdbc:postgresql://${CLOUDSERVICE_DB_HOST}:${CLOUDSERVICE_DB_PORT}/${CLOUDSERVICE_DB_NAME}
        username: ${CLOUDSERVICE_DB_USERNAME}
        password: ${CLOUDSERVICE_DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        open-in-view: false
        show-sql: true
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.format_sql: true
logging:
    level:
        org:
            springframework:
                security: debug
