spring:
  datasource:
    url: jdbc:postgresql://${CLOUDSERVICE_DB_HOST:localhost}:${CLOUDSERVICE_DB_PORT:5432}/${CLOUDSERVICE_DB_NAME:cloudservice}
    username: ${CLOUDSERVICE_DB_USERNAME:postgres}
    password: ${CLOUDSERVICE_DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

logging:
  level:
    aaagt:
      cloudservice:
        security:
          config:
            authentication: debug
          handler: debug
    org:
      springframework:
        security: debug

aaagt:
  cloudservice:
    jwt:
      token-issuer: "aaagt"
      token-secret: "cloudservice-secret!"
      token-expiry: 300 # seconds
